// Generated by CoffeeScript 1.3.3
(function() {
  var Dynasaur, Model, dynamo;

  dynamo = require('dynamo');

  Model = require('./model');

  Dynasaur = (function() {

    Dynasaur.prototype.models = {};

    Dynasaur.prototype.model_instances = [];

    function Dynasaur(aws_credentials) {
      var dynamo_client;
      this.aws_credentials = aws_credentials;
      dynamo_client = dynamo.createClient(this.aws_credentials);
      this.dynamo_db = dynamo_client.get('us-west-1');
    }

    Dynasaur.prototype.model = function(name, schema) {
      var model_type, table,
        _this = this;
      model_type = new Model(name, schema);
      this.models[name] = model_type;
      table = this.dynamo_db.get(name);
      table.fetch(function(err, table) {
        if (err) {
          return _this.dynamo_db.add(name, schema).save(function(err, table) {
            return table.watch(function(err, table) {
              console.log('Table created -> successfully retrieved');
              return model_type.setTable(table);
            });
          });
        } else {
          console.log('Table exists -> successfully retrieved');
          return model_type.setTable(table);
        }
      });
      return model_type;
    };

    return Dynasaur;

  })();

  module.exports = Dynasaur;

}).call(this);
