// Generated by CoffeeScript 1.3.3
(function() {
  var Model, ModelInstance,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ModelInstance = require('./ModelInstance');

  Model = (function() {

    function Model(name, schema) {
      this.name = name;
      this.schema = schema;
      this["new"] = __bind(this["new"], this);

      this.setTable = __bind(this.setTable, this);

      this.instances = [];
      this;

    }

    Model.prototype.setTable = function(table) {
      console.log(table);
      this.table = table;
      return this.unpauseInstances();
    };

    Model.prototype.unpauseInstances = function() {
      var instance, _i, _len, _ref, _results;
      _ref = this.instances;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        instance = _ref[_i];
        _results.push(instance.unpause());
      }
      return _results;
    };

    Model.prototype["new"] = function() {
      var instance;
      instance = new ModelInstance(this);
      this.instances.push(instance);
      return instance;
    };

    return Model;

  })();

  module.exports = Model;

}).call(this);
