// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(dynasaur) {
    var BlogPost, blog_post_schema;
    blog_post_schema = {
      attributes: {
        author: String,
        title: String,
        body: String,
        date: Number
      },
      index: [
        {
          type: 'hash',
          field: 'author'
        }, {
          type: 'range',
          fields: ['title', 'date']
        }
      ]
    };
    return BlogPost = dynasaur.model('BlogPost', blog_post_schema);
  };

}).call(this);
